baseURL = "https://tauchenmitsplitti.ch/"
languageCode = "de-ch"
title = "Tauchen mit Martin Splitt - PADI Tauchlehrer"
theme = "hugo-story"
unused = 0 #is just for git to do its thing

disableKinds = ["taxonomy", "taxonomyTerm", "section"]

[Params]
    author = "Martin Splitt"
    description = "Tauchen in der Schweiz mit PADI Tauchlehrer Martin Splitt"
    logo = "images/logo.png"
    favicon = true

[Params.social]
    instagram = "https://instagram.com/the_splitti"
    facebook = "https://www.facebook.com/martin.splitt2"
    youtube = "https://www.youtube.com/channel/UCJiwpzoexEK7aHUW7rOZbgQ"

[Params.Organization]
    name = "Tauchen mit Splitti"
    description = "Tauchen lernen in der Schweiz mit PADI Tauchlehrer Martin Splitt"
    location = "Zurich, Switzerland"

[menu]
[[menu.main]]
identifier = ""
url = "/"
name = "Start"
weight = 1

[[menu.main]]
identifier = "Tauchkurse"
url = "/#tauchkurse"
name = "Kurse"
weight = 2

#[[menu.main]]
#identifier = "Donnerstagstauchen"
#url = "/donnerstagstauchen"
#name = "Donnerstagstauchen"
#weight = 3

#[[menu.main]]
#identifier = "Sonntagstauchen"
#url = "/sonntagstauchen"
#name = "Sonntagstauchen"
#weight = 4

[[menu.main]]
identifier = "Tauchen gehen"
url = "/#kontakt"
name = "Tauchen gehen"
weight = 5

[[menu.main]]
identifier = "PADI Tauchlehrer Martin Splitt"
url = "/tauchlehrer-martin-splitt"
name = "Über mich"
weight = 6

[[menu.main]]
identifier = "Tauchen in der Schweiz"
url = "/tauchen-in-der-schweiz"
name = "Tauchen in der Schweiz"
weight = 7
